# Generated by Django 6.1.1 on 2026-10-05 12:17

import books.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('author', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('isbn', models.CharField(unique=True, validators=[books.validators.IsbnValidator()])),
                ('genre', models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Fantasy', 'Fantasy'), ('Science', 'Science'), ('Romance', 'Romance')], default='Non-Fiction', max_length=30)),
                ('language', models.CharField(choices=[('BG', 'Bulgarian'), ('EN', 'English'), ('FR', 'French'), ('GR', 'German'), ('Other', 'Other')], default='Other', max_length=10)),
                ('pages', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('publishing_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField()),
                ('slug', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
